SELECT CONCAT('/home/grep/src/', UFILE.BOARD_ID, '/', UFILE.FILE_ID, UFILE.FILE_NAME, UFILE.FILE_EXT) AS FILEPATH
FROM USED_GOODS_FILE AS UFILE JOIN USED_GOODS_BOARD as UBOARD
ON UFILE.BOARD_ID = UBOARD.BOARD_ID
WHERE UBOARD.VIEWS = 
    (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)

ORDER BY FILEPATH DESC