SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH , '%Y-%m-%d') as DATE_OF_BIRTH 
FROM MEMBER_PROFILE 
WHERE MONTH(DATE_OF_BIRTH) = 3 and GENDER = 'W'and TLNO is not null
ORDER BY MEMBER_ID;

#DATE_FORMAT(x,y) - x의 날짜 값의 형태를 y처럼 변경해줘