-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,"%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH LIKE '%03%' 
    AND GENDER LIKE 'W'
    AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;

# 이때 전화번호가 NULL인 경우는 출력대상에서 제외시켜 주시고,
# => AND TNLO IS NOT NULL
# 3월, 여성회원, IS NOT NULL